### ISSUE TITLE
faltan test

### ISSUE THREAD

**Issue by bigotes0invisibles** [HugoVS26/202309-w9ch1-hugo-veiga#24]
-te recomiendo empezar por test unitarios: como FlimCard
-configura el msw para los hooks: https://mswjs.io/
-cuando tengas problemas con el store te recomiendo ver esta pagina https://redux.js.org/usage/writing-tests#connected-components

**Comment by HugoVS26** [comment]
Ayer no me dio tiempo, me pongo a mirar testing, gracias!
